### PR TITLE
Update SampleApplication.js

### PR DESCRIPTION
**Pull request by vlamorozov**
cursor grab -- don't visible in chrome Version 88.0 in linux mate. visible in fireFox
cursor grabbing -- visible in chrome and firefox. Image this cursor very  similar grab

### CODE REVIEW

**Comment by yGuy** [comment]
That's strange. Is that a Linux Mate only bug? Because it seems this has been fixed in Chrome since version 68...

https://developer.mozilla.org/en-US/docs/Web/CSS/cursor#Browser_compatibility

**Comment by vlamorozov** [comment]
My OS 
NAME="Linux Mint"
VERSION="19.3 (Tricia)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 19.3"
VERSION_ID="19.3"
VERSION_CODENAME=tricia
UBUNTU_CODENAME=bionic

My browsers: 
google chrome Version 88.0.4315.5 (Official Build) dev (64-bit)-- don't visible grab cursor
opera Version72.0.3815.378-- don't visible grab cursor
fifefox browser developer version 84.0b3 (64-bit) - visible grab cursor

**Comment by michabaur** [comment]
Seems to be specific to that system. According to the docs, grab is available in Chrome, and it works as expected in our tests.

**Comment by yGuy** [comment]
This is likely a regression in Chrome, for these systems. At least there [have been some reports that suggest that](https://bugs.chromium.org/p/chromium/issues/detail?id=376156). I don't think every site should use the proposed workaround with a different icon, but it should really be fixed in Chrome.

**Pull request closed without merging**
